### ISSUE TITLE
Stproxy doesnt work on windows machines

### ISSUE THREAD

**Issue by bftaylor** [schwark/stproxy#1]
I set this up running stproxy-windows-amd64 -d \progra~1\alarmcom  . When it runs it show the following error warning no config file using defaults: open \progra~1\alarmcom/config.json: The system cannot find the file specified.  The file is there so tthe error is likeli the forward slash that gets appended.

**Comment by schwark** [comment]
just to be clear, it still runs and just shows a warning, or it is just dying?

**Comment by bftaylor** [comment]
Ok I downloaded the new one changed to -d config_file (before it was path to config, that gave a handle error so I added the file) and now it shows read proxy configuration, yeah. That said, when I start the driver I see: 2022/09/20 15:49:38 Read proxy configuration: {map[1:https://www.alarm.com] 8081}2022/09/20 15:49:38 Server initialized...2022/09/20 15:49:38 Proxy Server Started[SSDP] 2022/09/20 15:49:38 joined group 239.255.255.250:1900 on Ethernet (#16)[SSDP] 2022/09/20 15:49:38 joined group 239.255.255.250:1900 on Ethernet 2 (#9)[SSDP] 2022/09/20 15:49:38 joined group 239.255.255.250:1900 on Loopback Pseudo-Interface 1 (#1)[SSDP] 2022/09/20 15:49:38 SSDP advertise on: 224.0.0.1:1900[SSDP] 2022/09/20 15:51:18 sent alive[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:36 received M-SEARCH MAN="ssdp:discover" ST=ssdp:all from 192.168.0.196:3942[SSDP] 2022/09/20 15:52:44 failed to handle message: unexpected EOF[SSDP] 2022/09/20 15:52:44 failed to handle message: unexpected EOF And it never shows up in nearby devices. Is there something else I should check? Brian Taylor From: Schwark SatyavoluSent: Tuesday, September 20, 2022 2:57 PMTo: schwark/stproxyCc: bftaylor; AuthorSubject: Re: [schwark/stproxy] Stproxy doesnt work on windows machines (Issue #1) Closed #1 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by schwark** [comment]
the unexpected EOF is fixed in the latest driver version (no change to stproxy)..

**Comment by bftaylor** [comment]
Thanks, For the most part things now seem to work except arming. So what I am seeing, everything has now showed up and appears to be going to alarm.comWhen I select Arm Away, the UI indicates armed, but alarm.com doesn’t actually armWhen I select Arm Stay, the UI indicates armed, but alarm.com doesn’t actual armWhen I select Disarm, the UI indicates armed and alarm.com signals the system has been disarmed Any thoughts on what I can do to diagnose, 2 factor is off and the fact disarming is working and notifying me says the flow is overall working Brian Taylor From: Schwark SatyavoluSent: Wednesday, September 21, 2022 8:13 PMTo: schwark/stproxyCc: bftaylor; AuthorSubject: Re: [schwark/stproxy] Stproxy doesnt work on windows machines (Issue #1) the unexpected EOF is fixed in the latest driver version (no change to stproxy)..—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bftaylor** [comment]
It runs with the default values (not sure what those are) Brian Taylor From: Schwark SatyavoluSent: Tuesday, September 20, 2022 2:43 PMTo: schwark/stproxyCc: bftaylor; AuthorSubject: Re: [schwark/stproxy] Stproxy doesnt work on windows machines (Issue #1) just to be clear, it still runs and just shows a warning, or it is just dying?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
